project_id: "881052"
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /packages/i18n/src/po/en.po
    translation: /packages/i18n/src/po/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        es-ES: es
        pt-PT: pt
