import { oc } from "@orpc/contract";
import { z } from "zod";
import {
  BackupCreateOutput,
  BackupScheduleOutput,
  BackupsListOutput,
  BatchWatchInput,
  ContinueWatchingOutput,
  CreateIntegrationInput,
  DashboardRecommendationsOutput,
  DashboardStatsOutput,
  DiscoverInput,
  DiscoverOutput,
  FilenameParam,
  GenresOutput,
  IdParam,
  IntegrationOutput,
  IntegrationsListOutput,
  IntegrationTokenOutput,
  LibraryOutput,
  MediaTypeParam,
  PersonDetailOutput,
  PersonResolveOutput,
  PopularOutput,
  ProviderParam,
  QuickAddOutput,
  RegistrationOutput,
  SearchInput,
  SearchOutput,
  StatsInput,
  StatsOutput,
  SystemStatusOutput,
  TitleDetailOutput,
  TitleRecommendationsOutput,
  TitleResolveOutput,
  TmdbIdTypeParam,
  ToggleRegistrationInput,
  ToggleUpdateCheckInput,
  TrendingOutput,
  TriggerJobInput,
  TriggerJobOutput,
  UpdateCheckOutput,
  UpdateNameInput,
  UpdateRatingInput,
  UpdateScheduleInput,
  UpdateStatusInput,
  UserInfoOutput,
} from "./schemas";

export const contract = {
  titles: {
    detail: oc.input(IdParam).output(TitleDetailOutput),
    resolve: oc.input(TmdbIdTypeParam).output(TitleResolveOutput),
    updateStatus: oc.input(UpdateStatusInput),
    updateRating: oc.input(UpdateRatingInput),
    watchMovie: oc.input(IdParam),
    watchAll: oc.input(IdParam),
    userInfo: oc.input(IdParam).output(UserInfoOutput),
    recommendations: oc.input(IdParam).output(TitleRecommendationsOutput),
  },
  episodes: {
    watch: oc.input(IdParam),
    unwatch: oc.input(IdParam),
    batchWatch: oc.input(BatchWatchInput),
  },
  seasons: {
    watch: oc.input(IdParam),
    unwatch: oc.input(IdParam),
  },
  people: {
    detail: oc.input(IdParam).output(PersonDetailOutput),
    resolve: oc
      .input(z.object({ tmdbId: z.number().int() }))
      .output(PersonResolveOutput),
  },
  dashboard: {
    stats: oc.output(DashboardStatsOutput),
    continueWatching: oc.output(ContinueWatchingOutput),
    library: oc.output(LibraryOutput),
    recommendations: oc.output(DashboardRecommendationsOutput),
  },
  explore: {
    trending: oc.input(MediaTypeParam).output(TrendingOutput),
    popular: oc.input(MediaTypeParam).output(PopularOutput),
    genres: oc.input(MediaTypeParam).output(GenresOutput),
  },
  search: oc.input(SearchInput).output(SearchOutput),
  discover: oc.input(DiscoverInput).output(DiscoverOutput),
  stats: oc.input(StatsInput).output(StatsOutput),
  systemStatus: oc.output(SystemStatusOutput),
  integrations: {
    list: oc.output(IntegrationsListOutput),
    create: oc.input(CreateIntegrationInput).output(IntegrationOutput),
    delete: oc.input(ProviderParam),
    regenerateToken: oc.input(ProviderParam).output(IntegrationTokenOutput),
  },
  admin: {
    backups: {
      list: oc.output(BackupsListOutput),
      create: oc.output(BackupCreateOutput),
      delete: oc.input(FilenameParam),
      schedule: oc.output(BackupScheduleOutput),
      updateSchedule: oc.input(UpdateScheduleInput),
    },
    registration: oc.output(RegistrationOutput),
    toggleRegistration: oc.input(ToggleRegistrationInput),
    updateCheck: oc.output(UpdateCheckOutput),
    toggleUpdateCheck: oc.input(ToggleUpdateCheckInput),
    triggerJob: oc.input(TriggerJobInput).output(TriggerJobOutput),
  },
  account: {
    updateName: oc.input(UpdateNameInput),
  },
  watchlist: {
    quickAdd: oc.input(TmdbIdTypeParam).output(QuickAddOutput),
  },
};
